export const carCategory = [
  { id: crypto.randomUUID(), src: "empty-bg.svg", name: "MPV" },
  { id: crypto.randomUUID(), src: "empty-bg.svg", name: "Hatchback" },
  { id: crypto.randomUUID(), src: "empty-bg.svg", name: "Sedan" },
  { id: crypto.randomUUID(), src: "empty-bg.svg", name: "SUV" },
  { id: crypto.randomUUID(), src: "empty-bg.svg", name: "VAN" },
  { id: crypto.randomUUID(), src: "empty-bg.svg", name: "Jeep" },
  { id: crypto.randomUUID(), src: "empty-bg.svg", name: "Coupe" },
  { id: crypto.randomUUID(), src: "empty-bg.svg", name: "Wagon" },
  { id: crypto.randomUUID(), src: "empty-bg.svg", name: "Double Cabin" },
];

export const carData = [
  {
    id: crypto.randomUUID(),
    title: "Nama kendaraan",
    src: "/empty-bg.svg",
    price: 120000000,
    seller: "Orang 1",
    location: "Kota Administrasi",
  },
  {
    id: crypto.randomUUID(),
    title: "Nama kendaraan",
    src: "/empty-bg.svg",
    price: 120000000,
    seller: "Orang 1",
    location: "Kota Administrasi",
  },
  {
    id: crypto.randomUUID(),
    title: "Nama kendaraan",
    src: "/empty-bg.svg",
    price: 120000000,
    seller: "Orang 1",
    location: "Kota Administrasi",
  },
  {
    id: crypto.randomUUID(),
    title: "Nama kendaraan",
    src: "/empty-bg.svg",
    price: 120000000,
    seller: "Orang 1",
    location: "Kota Administrasi",
  },
  {
    id: crypto.randomUUID(),
    title: "Nama kendaraan",
    src: "/empty-bg.svg",
    price: 120000000,
    seller: "Orang 1",
    location: "Kota Administrasi",
  },
  {
    id: crypto.randomUUID(),
    title: "Nama kendaraan",
    src: "/empty-bg.svg",
    price: 120000000,
    seller: "Orang 1",
    location: "Kota Administrasi",
  },
  {
    id: crypto.randomUUID(),
    title: "Nama kendaraan",
    src: "/empty-bg.svg",
    price: 120000000,
    seller: "Orang 1",
    location: "Kota Administrasi",
  },
  {
    id: crypto.randomUUID(),
    title: "Nama kendaraan",
    src: "/empty-bg.svg",
    price: 120000000,
    seller: "Orang 1",
    location: "Kota Administrasi",
  },
];
